version: '3.3'
services:
    mysql:
        image: 'mysql:8'
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment:
            - MYSQL_ROOT_PASSWORD=opwer384
        volumes:
            - ~/db_data:/var/lib/mysql
        network_mode: db_network
        hostname: mysql
        restart: always
        
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
          - 8080
        labels:
          - "traefik.enable=true"

          # - "traefik.http.middlewares.adminer-https.redirectscheme.scheme=https"

          - 'traefik.http.routers.adminerhttp.entrypoints=web'
          - 'traefik.http.routers.adminerhttp.rule=Host(`adminer.loc`)'
          # - "traefik.http.routers.adminerhttp.middlewares=adminer-https"

          - "traefik.http.routers.adminer.rule=Host(`adminer.loc`)"
          - "traefik.http.routers.adminer.entrypoints=websecure"
          - "traefik.http.routers.adminer.tls=true"
          - "traefik.http.services.adminer.loadbalancer.server.port=8080"
        networks:
          - db_network
          - traefik_net
networks:
  db_network:
    external: true
    
  traefik_net:
    external: true
