version: "3"
services:
    smtp4dev:
        image: rnwood/smtp4dev
        container_name: smtpdev
        ports:
            - 3000:80
            - 2525:25
        labels:
            - "traefik.enable=true"

            # - "traefik.http.middlewares.${DOCKER_NAME}-https.redirectscheme.scheme=https"

            - 'traefik.http.routers.${DOCKER_NAME}.entrypoints=web'
            - 'traefik.http.routers.${DOCKER_NAME}.rule=Host(`${DOCKER_NAME}.loc`)'
            # - "traefik.http.routers.${DOCKER_NAME}.middlewares=${DOCKER_NAME}-https"

            - "traefik.http.routers.${DOCKER_NAME}https.rule=Host(`${DOCKER_NAME}.loc`)"
            - "traefik.http.routers.${DOCKER_NAME}https.entrypoints=websecure"
            - "traefik.http.routers.${DOCKER_NAME}https.tls=true"
            - "traefik.http.services.${DOCKER_NAME}https.loadbalancer.server.port=3000"
        networks:
            - traefik_net

networks:
  traefik_net:
    external: true
